spring: 
  datasource: 
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bank1?useUnicode=true
    username: root
    password: 52LDforever
    
logging: 
  level:
    root: info
    '[org.springframework.web]': info
    '[com.wy]': debug
  file:
    path: E:\tmp\logs