spring:
  application:
    name: dream-study-transaction-tcc-global
  profiles:
    active: dev,hmily
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server: 
  port: 55581
  max-http-header-size: 10000000
  servlet:
    context-path: /tcc-global

eureka:
  instance:
    hostname: localhost
    # 每隔2s向注册中心发送心跳包,张明自己还没有宕机
    lease-expiration-duration-in-seconds: 2
    # 当多长时间没有收到心跳包的信息时,从注册中心中剔除本服务
    lease-renewal-interval-in-seconds: 10
    # 通知注册中心,本服务实例以IP作为链接,而不是取机器名
    prefer-ip-address: true
    # 本服务实例的唯一ID
    instance-id: dream-study-transaction-tcc-global
  client: 
    service-url:
      defaultZone: http://${eureka.instance.hostname}:55550/eureka/
 
management: 
  endpoints:
    web:
      exposure:
        include:
        - "*"
        
feign:
  hystrix:
    enabled: true
  compression:
    request:
      # 配置请求GZIP压缩
      enabled: true
      # 配置压缩支持的MIME TYPE
      mime-types: ["text/xml","application/xml","application/json"]
      # 配置压缩数据大小的下限
      min-request-size: 2048
    response:
      # 配置响应GZIP压缩
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 设置熔断超时时间,默认1000毫秒
            timeoutInMilliseconds: 1000
        timeout:
          # 打开超时熔断功能,默认true
          enabled: true

ribbon:
  # 设置连接超时时间,默认2000毫秒
  ConnectTimeout: 600
  # 设置读取超时时间,默认5000好眠
  ReadTimeout: 6000
  # 对所有操作请求都进行重试,默认false
  OkToRetryOnAllOperations: true
  # 切换实例的重试次数,默认1
  MaxAutoRetriesNextServer: 2
  # 对当前实例的重试次数,默认0
  MaxAutoRetries: 1